server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/property_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        multiTenancy: SCHEMA

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/urbannest-system

  application:
    name: demo
