spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/urbannest_db
    username: urbannest
    password: urbannest

logging:
  level:
    com.multitenant: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
