package com.keycloak.demo.module.client.repository;

import com.keycloak.demo.module.client.entity.Client;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;
import java.util.UUID;

/**
 * Spring Data JPA repository for the Client entity.
 *
 * AUTOMATIC TENANT SCOPING:
 * -------------------------
 * Every query issued through this repository is automatically scoped to the current
 * tenant's PostgreSQL schema. Here is how that works:
 *
 *   1. An incoming request carries a JWT with the tenant_id attribute.
 *   2. A tenant-resolution filter (or interceptor) extracts that tenant_id and stores
 *      it in TenantContext (a ThreadLocal holder).
 *   3. Hibernate's multi-tenant ConnectionProvider reads TenantContext and sets the
 *      PostgreSQL search_path to the tenant's schema (e.g., SET search_path TO tenant_acme).
 *   4. All SQL generated by this repository -- findAll, findById, save, custom finders --
 *      hits the "clients" table inside that schema only.
 *
 * This means you never need to add a "WHERE tenant_id = ?" clause manually.
 * Data isolation is enforced at the connection/schema level, making accidental
 * cross-tenant data leaks structurally impossible.
 *
 * NOTE ON registerClient():
 * During client self-registration (a public endpoint with no JWT), the ClientService
 * sets TenantContext manually before calling repository methods, and clears it in a
 * finally block. This is the one case where tenant context is not set by the filter.
 */
@Repository
public interface ClientRepository extends JpaRepository<Client, UUID> {

    /**
     * Look up a client by their Keycloak user ID (the JWT "sub" claim).
     * Primary use: loading the logged-in client's own profile from their token.
     * Returns Optional.empty() if no client exists with that keycloakId in this tenant's schema.
     */
    Optional<Client> findByKeycloakId(String keycloakId);

    /**
     * Look up a client by email address within the current tenant schema.
     * Useful for admin searches or checking if a specific email is already registered.
     */
    Optional<Client> findByEmail(String email);

    /**
     * Existence check by email -- used during registration to prevent duplicate accounts.
     * More efficient than findByEmail() when you only need a boolean answer, because
     * Spring Data translates this to a SELECT EXISTS(...) query.
     */
    boolean existsByEmail(String email);

    /**
     * Paginated query for clients filtered by their active/inactive status.
     * Used when company admins want to see only active clients or review deactivated ones.
     * Spring Data handles the pagination (LIMIT/OFFSET) and sorting automatically
     * based on the Pageable parameter.
     */
    Page<Client> findByIsActive(boolean isActive, Pageable pageable);
}
