package com.keycloak.demo.master.entity;

import com.keycloak.demo.common.enums.TenantStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * Tenant Entity -- The central registry of all companies (tenants) in the system.
 *
 * This table lives in the PUBLIC (master) schema of PostgreSQL. It is the "phone book" that
 * the platform uses to know which companies exist, what their database schema is called,
 * and what state they are in.
 *
 * In this schema-per-tenant architecture, every company gets its own isolated PostgreSQL schema
 * (e.g., "tenant_acme_corp") for its business data. But BEFORE any of that can happen, the
 * company must first have a row here in the public.tenants table.
 *
 * Lifecycle of a Tenant row:
 *   1. PROVISIONING -- Row created, schema + Keycloak resources being set up.
 *   2. ACTIVE       -- Everything is ready; the company's users can log in and use the app.
 *   3. SUSPENDED    -- SUPER_ADMIN temporarily disabled the tenant (e.g., non-payment).
 *                      Users cannot access their data, but nothing is deleted.
 *   4. DELETED      -- Tenant is soft-deleted. No reactivation allowed.
 *
 * Who reads this table?
 *   - TenantConnectionProvider: looks up schema_name to route DB connections to the right schema.
 *   - TenantProvisioningService: creates new rows during company registration.
 *   - TenantService: CRUD operations used by SUPER_ADMIN dashboard.
 *   - Security filters: validate that a tenant exists and is ACTIVE before allowing API access.
 */
@Entity
// Explicitly pinned to the "public" schema so Hibernate never tries to put this table inside
// a tenant schema. Without this, the dynamic schema routing could accidentally look for the
// "tenants" table inside a tenant's own schema, which would fail.
@Table(name = "tenants", schema = "public")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Tenant {

    /**
     * Internal primary key (UUID). Used for foreign keys and internal references only.
     * Never exposed in URLs -- we use tenantId (the slug) for that.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Human-readable, URL-safe identifier derived from the company name (e.g., "acme-corp").
     * This is what appears in API paths, JWT claims, and Keycloak group names.
     * Generated by TenantProvisioningService.generateTenantSlug().
     * Must be unique -- two companies cannot have the same slug.
     */
    @Column(name = "tenant_id", unique = true, nullable = false, length = 50)
    private String tenantId;

    /**
     * The company's display name as provided during registration (e.g., "Acme Corporation").
     * Used in UI headers and admin dashboards. Can contain spaces and special characters.
     */
    @Column(name = "company_name", nullable = false)
    private String companyName;

    /**
     * The PostgreSQL schema name assigned to this tenant (e.g., "tenant_acme_corp").
     * Constructed as: AppConstants.TENANT_SCHEMA_PREFIX + tenantId.
     * This is what the TenantConnectionProvider uses to SET search_path when routing
     * database queries for this tenant's data.
     * Must be unique -- each tenant gets exactly one isolated schema.
     */
    @Column(name = "schema_name", unique = true, nullable = false, length = 100)
    private String schemaName;

    /**
     * Current lifecycle state of the tenant. Stored as a string in the DB (not an ordinal)
     * so it is human-readable in direct SQL queries.
     * See TenantStatus enum for valid values: PROVISIONING, ACTIVE, SUSPENDED, DELETED.
     * The schema routing and security filters check this before allowing any tenant access.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TenantStatus status;

    /**
     * Email address of the company owner / initial admin user.
     * This is the person who registered the company. They get the ADMIN role in Keycloak.
     * Also used as a uniqueness check -- one email can only own one tenant.
     */
    @Column(name = "owner_email", nullable = false)
    private String ownerEmail;

    /**
     * The Keycloak user ID of the owner. Set during provisioning after the Keycloak user
     * is successfully created. This links the tenant record back to the identity provider.
     * Initially null during the PROVISIONING step, populated once Keycloak user creation succeeds.
     */
    @Column(name = "owner_keycloak_id")
    private String ownerKeycloakId;

    /**
     * Foreign key to the subscription_plans table. Determines what limits apply to this
     * tenant (max users, max clients, available features). Can be null if no plan is
     * assigned yet (e.g., during initial provisioning or on a free tier).
     */
    @Column(name = "subscription_plan_id")
    private UUID subscriptionPlanId;

    /**
     * Timestamp when this tenant record was first created. Set automatically by Hibernate
     * on insert and never updated afterward. Useful for audit trails and "member since" displays.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Timestamp of the last modification to this record. Auto-updated by Hibernate on every save.
     * Tracks when status changes, plan upgrades, or other modifications occurred.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;
}
